### ISSUE TITLE
Your 'access_token' token could not be verified (The token is not yet valid (iat))

### ISSUE THREAD

**Issue by tavaresarthur** [pop-srw/streamlit-cognito-auth#13]
When testing `CognitoAuthenticator`, login fails and I get the error below. A colleague based on a different time zone was able to successfully login with the same credentials.

```bash
INFO:streamlit_cognito_auth.auth:Could not log in
error
ERROR:streamlit_cognito_auth.auth:Your 'access_token' token could not be verified (The token is not yet valid (iat)).
Traceback (most recent call last):
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\choppa-dJsBdwSi-py3.11\Lib\site-packages\streamlit_cognito_auth\utils.py", line 15, in verify_access_token
    claims = u.verify_token(token, "access_token", "access")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\choppa-dJsBdwSi-py3.11\Lib\site-packages\pycognito\__init__.py", line 266, in verify_token
    raise TokenVerificationException(
pycognito.exceptions.TokenVerificationException: Your 'access_token' token could not be verified (The token is not yet valid (iat)).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\choppa-dJsBdwSi-py3.11\Lib\site-packages\streamlit_cognito_auth\auth.py", line 265, in _set_state_login
    claims, user = verify_access_token(
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\choppa-dJsBdwSi-py3.11\Lib\site-packages\streamlit_cognito_auth\utils.py", line 20, in verify_access_token
    raise TokenVerificationException(e)
streamlit_cognito_auth.exceptions.TokenVerificationException: Your 'access_token' token could not be verified (The token is not yet valid (iat)).
INFO:streamlit_cognito_auth.auth:Could not log in
INFO:streamlit_cognito_auth.auth:_login was called, result: False
```

**Comment by pop-srw** [comment]
Thanks for reporting this issue with CognitoAuthenticator. The TokenVerificationException suggests that the issue is related to AWS Cognito configuration rather than our project's codebase.
Please double-check the following:

1. Ensure your AWS Cognito user pool is configured correctly (app client ID, secret, and user pool ID).
2. Confirm that the correct AWS region is set for Cognito in your configuration, especially since your colleague in a different time zone could log in successfully.

If the issue persists, please provide your CognitoAuthenticator configuration (obscuring sensitive info), the full traceback, and the AWS region of your Cognito user pool. We'll investigate further with these details.
